### ISSUE TITLE
UW Homework Solutions Removal Request

### ISSUE THREAD

**Issue by jsanders89** [Jebbs/JavaClass#2]
Hello,

My name is Jonathan and I work with the introductory computer science courses at the University of Washington. The posts in this repository contain solution code to some our homework assignments, specifically LetterInventory, Anagram, Critters, and Huffman.

https://github.com/Jebbs/JavaClass/tree/master/Anagram
https://github.com/Jebbs/JavaClass/tree/master/Critters
https://github.com/Jebbs/JavaClass/tree/master/Huffman

These posts' solution codes are indexed by Google, enabling current students to easily find them and cheat on their assignments.

Would you please remove the folders linked above or make them private in order to help us enforce our academic policy?

By removing these folders, you would be removing tools that our students could use in academic misconduct.

Thank you,
Jonathan Sanders
Intro Support, Computer Science & Engineering
University of Washington
jsanders@cs.washington.edu
More info on our course: http://courses.cs.washington.edu/courses/cse142/15su/

**Comment by Jebbs** [comment]
Oh, wow! I didn't even think about that. 

I will take these down this evening.

**Comment by Jebbs** [comment]
Code is removed, but since you can still view the repo history I will be deleting it.

If you need to contact me at all after that for what ever reason you can use my email associated with my github profile, dehaan.jeremiah@gmail.com.
